backend:
  enabled: true
  listener: 0.0.0.0:3000
  admin_password: '123'
prints:
  model:
    skipped_values: true
    metrics: false
  cycle:
    volatility: true
    cycle_start: true
    price: false
    target: true
    prediction: true
    accuracy: true
  manager:
    manager_init: true
    additional_manager_prints: true
behaviour:
  success_threshold: 0.125
  accuracy_capacity: 192
  predictions_capacity: 96
runtime:
  type: realtime
  with_training: false
  with_saves: true
  with_model: false
  cycle_type: loader
exchange:
  symbols:
  - BTCUSDT
  servers:
  - 127.0.0.1:3737
  main_exchange: binance
  timeframes:
    main: 15m
    background: 1m
mode: print
