model:
  name: "RF"
  n_trees: 100
  max_depth: 5
  seed: 42
  train_test_split:
    train_ratio: 0.8

backend:
  enabled: true
  listener: "0.0.0.0:3000"
  admin_password: "123"

data:
  success_threshold:
    minimum: 0.2
    default: 1.0
    maximum: 1.7
  accuracy_capacity: 192

prints:
  model_evualate: false
  cycle:
    volatility: true
    cycle_start: false
    price: false
    target: true
    prediction: true
    accuracy: true
  manager:
    manager_init: true
    additional_manager_prints: true

token:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - DOGEUSDT
  - ADAUSDT
  - XRPUSDT
  - SOLUSDT

cycle_type: "training"
mode: "print"
