model:
  type: "DecisionTree"
  params:
    kind: "DecisionTree"
    max_depth: 5
    min_samples_leaf: 100
    min_samples_split: 100
  train_test_split:
    train_ratio: 0.8
  metric: "ALL"
  seed: 42

backend:
  enabled: false
  listener: "0.0.0.0:3000"
  admin_password: "123"

servers:
  - "127.0.0.1:3737"

behaviour:
  success_threshold:
    minimum: 0.2
    default: 0.3
    maximum: 1.7
    ratio: 1.25
  risk_threshold:
    minimum: 0.5
    default: 1.0
    maximum: 3.0
  trading_mode_value:
    minimum: -1.0
    default: 0.0
    maximum: 1.0
  accuracy_capacity: 192
  predictions_capacity: 96
  feedback_engine_capacity: 5

prints:
  model:
    skipped_values: true
    metrics: true
  cycle:
    volatility: true
    cycle_start: true
    price: false
    target: true
    prediction: true
    accuracy: true
  manager:
    manager_init: true
    additional_manager_prints: true

symbols:
  - SOLUSDT

runtime:
  type: "backtest"
  with_training: false
  cycle_type: "training"

main_exchange: "binance"

timeframes:
  main: "15m"
  background: "1m"
mode: "print"
